### ISSUE TITLE
Can't  load Application/Sonata/ApplicationSonataUserBundle

### ISSUE THREAD

**Issue by tmac14** [sonata-project/SonataUserBundle#902]
Hi, Im following the installation guide step-by-step and Im getting the next error:

````
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ApplicationSonataUserBundle" from namespace "Application\Sonata\UserBundle".
Did you forget a "use" statement for another namespace? in /home/josecostas/Programming/tuttocars/app/AppKernel.php:35
Stack trace:
#0 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
#1 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot()
#3 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(S in /home/josecostas/Programming/tuttocars/app/AppKernel.php on line 35

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ApplicationSonataUserBundle" from namespace "Application\Sonata\UserBundle".
Did you forget a "use" statement for another namespace? in /home/josecostas/Programming/tuttocars/app/AppKernel.php:35
Stack trace:
#0 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
#1 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot()
#3 /home/josecostas/Programming/tuttocars/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(S in /home/josecostas/Programming/tuttocars/app/AppKernel.php on line 35
`
```

The symfony version is 3.3.6 and it's a clear installation. Maybe there is the problem.
Im not an expert in symfony and github either and Im spanish (excuse me about my english level).
Please, tell me if you need more details about code and versions.

Thanks.

**Comment by tmac14** [comment]
Yes, thanks you. Im newbie.

**Comment by RaphArbuz** [comment]
Thanks @tarlepp and one shouldn't forget to run `composer update` after that.

**Comment by TELLO0815** [comment]
@tarlepp I have the same problem. I don't get it where to change. Can u specify for me the file please?

THX Mike
PS: Newbie ;-)

**Comment by tarlepp** [comment]
@TELLO0815 see your `composer.json` file on root of your project.

**Comment by TELLO0815** [comment]
THX
