### ISSUE TITLE
Fatal error: You have requested a non-existent parameter "twig.form.resources"

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataUserBundle#924]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.23.0             3.23.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.4.0              3.4.0              Symfony SonataBlockBundle
sonata-project/cache                     1.1.0              2.0.0              Cache library
sonata-project/core-bundle               3.5.1              3.5.1              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7              3.1.7              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              1.7.1              Lightweight Exporter library
sonata-project/formatter-bundle          3.2.3              3.2.3              Symfony SonataFormatterBundle
sonata-project/media-bundle              3.6.0              3.6.0              Symfony SonataMediaBundle
sonata-project/notification-bundle       3.2.0              3.2.0              Symfony SonataNotificationBundle
sonata-project/user-bundle               dev-master c322961 dev-master c322961 Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2  v2.8.2  Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.1  v3.1.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.3.10 v3.3.10 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0  v1.5.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0  v1.5.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0  v1.5.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0  v1.5.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0  v1.5.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0  v1.5.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3  v3.1.1  Symfony SwiftmailerBundle
symfony/symfony            v3.2.13 v3.3.10 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

I have installed `SonataUserBundle`. I'm trying to run `php bin/console`, and this is causing next error:
```
$ php bin/console 
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "twig.form.resources". in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(56): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('twig.form.resou...')
#1 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(124): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('twig.form.resou...')
#2 /home/vyshkant/www/ancientrus/vendor/sonata-project/user-bundle/DependencyInjection/SonataUserExtension.php(83): Symfony\Component\DependencyInjection\Container->getParameter('twig.form.resou...')
#3 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfon in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
```
The reason is next.

The `Sonata\UserBundle\DependencyInjection\SonataUserExtension` is trying to add custom form widgets:

https://github.com/sonata-project/SonataUserBundle/blob/c3229613121efbf8f0f8f09e2ec79d8476c4a165/DependencyInjection/SonataUserExtension.php#L81-L85

This function expects the parameter `twig.form.resources` is already set (and the `getParameter` call will not cause an error).

But this parameter might not be set. The `twig.form.resources` parameter is setting by the `TwigBundle` (it gets `twig.form_themes` **config parameter** and then setting `twig.form.resources` **container parameter**). So the `twig.form.resources` is not set before `TwigBundle` is not loaded.

When I modified my `AppKernel::registerBundles` and defined `TwigBundle` before the `SonataUserBundle`, I got rid of the error, shown above.

## Steps to reproduce
1) Install Symfony 3.2.*.
2) Install SonataUserBundle 4.x-dev and put line `new Sonata\UserBundle\SonataUserBundle()` in `AppKernel::registerBundles` **below** the line `new Symfony\Bundle\TwigBundle\TwigBundle()`.
3) Run `php bin/console`.

## Expected results
Default console output.

## Actual results
PHP Fatal error:
```
$ php bin/console 
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "twig.form.resources". in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(56): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('twig.form.resou...')
#1 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(124): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('twig.form.resou...')
#2 /home/vyshkant/www/ancientrus/vendor/sonata-project/user-bundle/DependencyInjection/SonataUserExtension.php(83): Symfony\Component\DependencyInjection\Container->getParameter('twig.form.resou...')
#3 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfon in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
```

## Ways to fix ##
I'm not sure what is the best way to fix this issue: we either have to check if the parameter `twig.form.resources` is set (`$container->hasParameter('twig.form.resources')`), or force the user to define the `SonataUserBundle` **after** the `TwigBundle` in `AppKernel::registerBundles` (or both).

In the first case we will not have a guarantee that the custom form widgets will be added.

The second case looks more reliable, but I'm not sure if this is correct from the point of view of the project ideology.

Any ideas? I'll gladly write PR.

**Comment by greg0ire** [comment]
I usually solve this kind of race conditions with a `PrependExtensionInterface` implementation: https://symfony.com/doc/current/bundles/prepend_extension.html Do you think it could be used in this case?
